site_name: Mastering Go
docs_dir: "doc"

nav:
    - Home:
        - index.md
    - CLI Tooling:
        - cli/general.md
        - Modules: cli/go_mod.md
    - Fundamentals:
        - Variables and Constants: fundamentals/vars.md
        - Code Blocks: fundamentals/blocks.md
        - Control Structures: basics/control_flow.md
        - Files Handle: basics/handle_files.md
        - Literals Types:
            - fundamentals/literals.md
            - Integers: fundamentals/literals/integers.md
            - Floats: fundamentals/literals/floats.md
            - Strings/Runes: fundamentals/literals/strings.md
        - Composite Types:
            - Array: fundamentals/composite/array.md
            - Slice: fundamentals/composite/slice.md
            - Maps: fundamentals/composite/maps.md
            - Structs: structs/structs.md
            - Pointers: pointers.md
        - Functions:
            - functions/basic_func.md
            - Deeper in Functions: functions/func_as_value.md
            - Defer: functions/defer.md
        - Built-In:
            - Functions: fundamentals/built_in/functions.md
        # Erros, Panic, Recover
    - Errors: errors/error_basic.md
    - Packages & Modules: basics/packages.md
    - Interface: structs/interface.md
    - Generics: generics.md
    - Context: context.md
    - Network: 
        # add echo https://echo.labstack.com/ https://github.com/labstack/echo
        - API: https_network/api.md
        - File Server: https_network/file_server.md
        - HTTP Request: https_network/request.md
        - JSON: https_network/json.md
        - Templates: https_network/templates.md
    - Multithreading:
        - Go Routines: multithreading/go_routines.md
        - Race Condition: multithreading/race_condition.md
        - Channels: multithreading/channels.md
        - Select: multithreading/select.md
    - Testing: testing/index.md
    - Databases:
        - Basic: db/basic.md
        - Migrations: db/migrations.md
        - SQLX Library: db/sqlx.md
    - Cobra CLI: cobra_cli/index.md
    - Projects: 
        - Get Address: projects/get_br_zipcode.md
    # Add Tecnicas: olhar o curso!
    - Patterns: 
        - Dependency Injection:
            - Wire: di/wire.md

theme:
  name: material
  language: en
  logo: images/go-logo.png
  favicon: images/go-logo.png
  font:
    text: Noto Sans SemiBold 600 
  palette:
      scheme: slate
      primary: black
      accent: yellow
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.code.annotate

plugins:
  - search

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
