site_name: Mastering Go
docs_dir: "doc"

nav:
  - Home: index.md
  - Basics:
      - Go Paradigms: basics/go_paradigm.md
      - Go CLI:
        - CLI General: basics/cli/general.md
        - go mod: basics/cli/go_mod.md
      - Packages, Modules and Workspaces: basics/packages.md
      - Variables and Data Types: basics/vars.md
      - Control Flow: basics/control_flow.md
      - Handle Files: basics/handle_files.md
  - Functions:
      - Basic: functions/index.md
  - Structs: 
      - Basic: structs/structs.md
      - Interface: structs/interface.md
  - Pointers: pointers.md
  - Generics: generics.md
  - Context: context.md
  - HTTP, Network, etc: 
      - API: https_network/api.md
      - File Server: https_network/file_server.md
      - HTTP Request: https_network/request.md
      - JSON: https_network/json.md
      - Templates: https_network/templates.md
  - Multithreading:
        - Go Routines: multithreading/go_routines.md
        - Race Condition: multithreading/race_condition.md
        - Channels: multithreading/channels.md
        - Select: multithreading/select.md
  - Testing: testing/index.md
  - Databases:
      - Basic: db/basic.md
      - Migrations: db/migrations.md
  - Cobra CLI: cobra_cli/index.md
  - Projects: 
      - Get Address: projects/get_br_zipcode.md

theme:
  name: material
  language: en
  logo: images/go-logo.png
  favicon: images/go-logo.png
  palette:
      scheme: slate
      primary: white
      accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.instant
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
