site_name: Mastering Go
docs_dir: "doc"

nav:
    - Home:
        - index.md
    - CLI Commands:
        - cli/general.md
        - go mod: cli/go_mod.md
    - Fundamentals of Go Programming:
        - Variables and Data Types: fundamentals/vars.md
        - Logic and Control Structures: basics/control_flow.md
        - Functions:
            - Basic: functions/index.md
        - Handle Files: basics/handle_files.md
        - Packages, Modules and Workspaces: basics/packages.md
        - Structs: 
            - Basic: structs/structs.md
            - Interface: structs/interface.md
        - Pointers: pointers.md
        - Generics: generics.md
    - Context: context.md
    - Network: 
        - API: https_network/api.md
        - File Server: https_network/file_server.md
        - HTTP Request: https_network/request.md
        - JSON: https_network/json.md
        - Templates: https_network/templates.md
    - Multithreading:
        - Go Routines: multithreading/go_routines.md
        - Race Condition: multithreading/race_condition.md
        - Channels: multithreading/channels.md
        - Select: multithreading/select.md
    - Testing: testing/index.md
    - Databases:
        - Basic: db/basic.md
        - Migrations: db/migrations.md
        - SQLX Library: db/sqlx.md
    - Cobra CLI: cobra_cli/index.md
    - Projects: 
        - Get Address: projects/get_br_zipcode.md
    - Patterns: 
        - Dependency Injection:
            - Wire: di/wire.md

theme:
  name: material
  language: en
  logo: images/go-logo.png
  favicon: images/go-logo.png
  palette:
      scheme: slate
      primary: blue
      accent: white
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.instant
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
